### PR TITLE
Update wattile

### PR DESCRIPTION
**Pull request by haneslinger**

### CODE REVIEW

**Comment by haneslinger** [comment]
Do we want the alfa ensemble model to make it in here?

**Comment by stephen-frank** [comment]
No, I don't think so; let's target 0.3. To test it on SkySpark we'll need to train one for at least one of the STM campus meters.

**Comment by haneslinger** [comment]
alrighty, I think we are ready then?

**Comment by haneslinger** [comment]
force push to rebase on top of develop

**Review by smithcommajoseph — APPROVED** [review]
Looks good to merge.

**Comment by stephen-frank** [comment]
Looks good to me; let's do it!

**Pull request closed without merging**
