### PR TITLE
Use nonroot user

### PR DESCRIPTION
**Pull request by haneslinger**
I was trying to test this but couldn't figure out how to bash into it. @stephen-frank, does the base image have bash?

```
heslinge at 12:19:34 in ~/Repos/Wattile (run-docker-as-non-root) 
🌟 docker run 2f81bf21e1d4 -it bin/bash
python: can't open file '/usr/src/app/bin/bash': [Errno 2] No such file or directory
>>> 
```

### CODE REVIEW

**Comment by stephen-frank** [comment]
I really don't know! But if the entry point is python is it a python prompt?

https://github.com/NREL/Wattile/blob/develop/Dockerfile#L18C1-L18C22

**Comment by stephen-frank** [comment]
I ran into this by having Python write files in Linux... it created them as root.root. So I think you could test it by creating a new file and then reading back its user and group?

**Comment by haneslinger** [comment]
> I really don't know! But if the entry point is python is it a python prompt?
> 
> https://github.com/NREL/Wattile/blob/develop/Dockerfile#L18C1-L18C22

`docker run 2f81bf21e1d4 -it bin/bash` overwrite the enterpoint as `bin/bash`

**Comment by stephen-frank** [comment]
Ok, I see.

**Comment by stephen-frank** [comment]
I haven't been able to test this yet. I'd like to test it with the SkySpark dev server. Can you explain what these lines do?

```
# use non root user. 
RUN groupadd -r user && useradd -r -g user user
USER user

ENTRYPOINT ["python"]
```

Does this add a user called "user" and a group called "user" and make Docker run as that user? If yes, is it possible to make the user a Docker build argument?

**Comment by stephen-frank** [comment]
I think I answered my own question; going to test over here... https://github.com/NREL/nrelWattileExt/pull/42

**Comment by haneslinger** [comment]
closed cause https://github.com/NREL/Wattile/pull/302

**Pull request closed without merging**
