### PR TITLE
Expanded test data sets

### PR DESCRIPTION
**Pull request by stephen-frank**
This PR is intended to address #258 and #260. Right now, it includes new CSV files to address #260 but the tests have not been updated for all combinations. Tests are set up to match what I think is the correct behavior based on how I was reading the pre-processing code (see `preprocessing_input_output.xlsx`).

@haneslinger Can you set up the combined test cases for #260 based on these fixtures?

### CODE REVIEW

**Comment by stephen-frank** [comment]
@haneslinger unsure why either test is failing. I fixed a couple errors, but it says the data frame from the CSV has 16 rows... which I don't understand because the CSV only has 4 rows. Not good enough with Python to figure it out.

**Comment by haneslinger** [comment]
I rebased because `roll_data` and `resample_data` were recently separated. We now have a test for each. 

I also parametrize the two tests so we test every right/left combo against the relevant file.

Finally, I reordered some of the columns in the ouput file to reflect the output. 

`test_roll_data` still fails tho, I believe because of issues with the  code base, not the tests. I'm looking into it.

**Comment by stephen-frank** [comment]
I was working off of main, not Janghyun's updated branch, so that could be why? @haneslinger I will try to catch you later today.

**Comment by JanghyunJK** [comment]
I was planning to work on something else but thanks to Eagle, I was to able to test these new data with latest Wattile. Hope this helps:

image

image

image

image

**Comment by JanghyunJK** [comment]
A bit more context for left/left scenario:

- Below are four different windows considered for resampling (in Wattile),
image

- The last window covering `07:15-07:20` (represented with label `07:15`) is grabbing data for `07:15:00 var1=15 var2=NaN`

- But since var2's value is NaN, all rolling stats result in NaN. the reference data actually puts 0 to those same places.

**Comment by stephen-frank** [comment]
I think the NaN result is generally correct. The CSV import may be pulling in empty cells as zeros. Original files should have empty cells in those NaN locations. I will double-check; I assembled the test output files by hand.

**Comment by stephen-frank** [comment]
@JanghyunJK There is an error in the Excel formula that is treating blank as zero; working on a fix. This may explain the failing tests now.

**Comment by stephen-frank** [comment]
Ok, passes tests! But I managed to mess up the formatting again in the process of pulling/merging changes.

**Review by JanghyunJK — APPROVED** [review]

**Review by haneslinger — APPROVED** [review]

**Pull request merged**
